dist: xenial
language: cpp

script:
  - mkdir build && cd build
  # - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$COMPILER
  - cmake ..
  - cmake --build .
  - ctest


# env:
#   - BUILD_TYPE=Release COMPILER=gcc-4.8
#   - BUILD_TYPE=Release COMPILER=gcc-4.9
#   - BUILD_TYPE=Release COMPILER=gcc-5
#   - BUILD_TYPE=Release COMPILER=gcc-6
#   - BUILD_TYPE=Release COMPILER=clang-3.9
#   - BUILD_TYPE=Release COMPILER=clang-4.0
#   - BUILD_TYPE=Debug COMPILER=gcc-4.8
#   - BUILD_TYPE=Debug COMPILER=gcc-4.9
#   - BUILD_TYPE=Debug COMPILER=gcc-5
#   - BUILD_TYPE=Debug COMPILER=gcc-6
#   - BUILD_TYPE=Debug COMPILER=clang-3.9
#   - BUILD_TYPE=Debug COMPILER=clang-4.0

before_install:
    - eval "${MATRIX_EVAL}"


matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    # works on Xenial
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test  # for libstdc++6 (>= 4.9)
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

    - os: osx
      osx_image: xcode12.2
    - os: osx
      osx_image: xcode11.6
    - os: osx
      osx_image: xcode10.3
