dist: trusty
language: cpp

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$COMPILER
  - cmake --build . -- VERBOSE=1
  - ctest -V


env:
  - BUILD_TYPE=Release COMPILER=gcc-4.8
  - BUILD_TYPE=Release COMPILER=gcc-4.9
  - BUILD_TYPE=Release COMPILER=gcc-5
  - BUILD_TYPE=Release COMPILER=gcc-6
  - BUILD_TYPE=Release COMPILER=clang-3.9
  - BUILD_TYPE=Release COMPILER=clang-4.0
  - BUILD_TYPE=Debug COMPILER=gcc-4.8
  - BUILD_TYPE=Debug COMPILER=gcc-4.9
  - BUILD_TYPE=Debug COMPILER=gcc-5
  - BUILD_TYPE=Debug COMPILER=gcc-6
  - BUILD_TYPE=Debug COMPILER=clang-3.9
  - BUILD_TYPE=Debug COMPILER=clang-4.0


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9
      - llvm-toolchain-trusty-4.0
    packages:
      # - g++-4.5
      # - g++-4.6
      # - g++-4.7
      - g++-4.8
      - g++-4.9
      - g++-5
      - g++-6
      - clang-3.9
      - clang-4.0

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode7.3
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode8.2
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode6.4
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode7.3
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode8.2
      env: BUILD_TYPE=Release

