build:

build_script:
  - set PATH=%PATH%;C:\MinGW\bin
  - mkdir build && cd build
  - cmake -G "%TOOLCHAIN_VERSION%" ..
  - cmake --build . --config %BUILD_TYPE% 

test_script:
  - cmd: "%BUILD_TYPE%\\julia julia.tga"
  - cmd: "%BUILD_TYPE%\\render render.tga"

environment:
  matrix:
    - TOOLCHAIN_VERSION: MinGW Makefiles
      BUILD_TYPE: Debug
    - TOOLCHAIN_VERSION: Visual Studio 14 Win64
      BUILD_TYPE: Release
    - TOOLCHAIN_VERSION: Visual Studio 12 Win64
      BUILD_TYPE: Release
    - TOOLCHAIN_VERSION: Visual Studio 14 Win64
      BUILD_TYPE: Debug
    - TOOLCHAIN_VERSION: Visual Studio 12 Win64
      BUILD_TYPE: Debug
    - TOOLCHAIN_VERSION: Visual Studio 14
      BUILD_TYPE: Release
    - TOOLCHAIN_VERSION: Visual Studio 12
      BUILD_TYPE: Release
    - TOOLCHAIN_VERSION: Visual Studio 14
      BUILD_TYPE: Debug
    - TOOLCHAIN_VERSION: Visual Studio 12
      BUILD_TYPE: Debug

