build_script:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -G "%TOOLCHAIN_VERSION%" ..
  - cmake --build . --config %BUILD_TYPE% 

test_script:
  - cmd: ctest -V -C %BUILD_TYPE%

environment:
  matrix:
    - TOOLCHAIN_VERSION: MinGW Makefiles
      BUILD_TYPE: Debug
    - TOOLCHAIN_VERSION: MinGW Makefiles
      BUILD_TYPE: Release
    - TOOLCHAIN_VERSION: Visual Studio 14 Win64
      BUILD_TYPE: Release
    - TOOLCHAIN_VERSION: Visual Studio 12 Win64
      BUILD_TYPE: Release
    - TOOLCHAIN_VERSION: Visual Studio 14 Win64
      BUILD_TYPE: Debug
    - TOOLCHAIN_VERSION: Visual Studio 12 Win64
      BUILD_TYPE: Debug
    - TOOLCHAIN_VERSION: Visual Studio 14
      BUILD_TYPE: Release
    - TOOLCHAIN_VERSION: Visual Studio 12
      BUILD_TYPE: Release
    - TOOLCHAIN_VERSION: Visual Studio 14
      BUILD_TYPE: Debug
    - TOOLCHAIN_VERSION: Visual Studio 12
      BUILD_TYPE: Debug

